### PR TITLE
Actually fix the JSON object bug

### PR DESCRIPTION
**Pull request by mdwalters**
This fixes the JSON Object bug, where it won't read objects in a array. This PR finally fixes that bug after a few months of trial and error.

### CODE REVIEW

**Comment by mdwalters** [comment]
@MikeDev101

**Comment by theotherhades** [comment]
*an array

**Comment by mdwalters** [comment]
ok

**Comment by mdwalters** [comment]
@MikeDev101 pls accept

**Comment by MikeDev101** [comment]
lol old merge

**Comment by mdwalters** [comment]
imagine begging you to do this for 2 months lmao

**Pull request merged**
